/// Source: account
table Account
	lineageTag: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

	/// Primary key | Source: account.accountid
	column accountid
		dataType: string
		isHidden
		isKey
		lineageTag: 11111111-2222-3333-4444-555555555555
		summarizeBy: none
		sourceColumn: accountid

		annotation SummarizationSetBy = Automatic

		annotation DataverseToPowerBI_LogicalName = accountid

	/// The name of the account | Source: account.name
	column 'Old Display Name'
		dataType: string
		lineageTag: 22222222-3333-4444-5555-666666666666
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Old Display Name
		description: The primary name of the account

		annotation SummarizationSetBy = Automatic

		annotation DataverseToPowerBI_LogicalName = name

		annotation UserCustomAnnotation = MyValue

	/// Revenue | Source: account.revenue
	column Revenue
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 33333333-4444-5555-6666-777777777777
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

		annotation DataverseToPowerBI_LogicalName = revenue

	measure 'Custom Measure' = SUM(Account[Revenue]) * 2
		formatString: $#,0.00
		lineageTag: 55555555-6666-7777-8888-999999999999

	measure 'Account Count' = COUNTROWS('Account')
		formatString: 0
		lineageTag: 77777777-8888-9999-aaaa-bbbbbbbbbbbb

	partition Account = m
		mode: directQuery
		source =
				let
				    Source = CommonDataServiceForApps.Database(DataverseURL)
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
